DELETE FROM auth.users;

DROP TABLE IF EXISTS usuario CASCADE;

DROP TABLE IF EXISTS cartao CASCADE;

DROP TABLE IF EXISTS perfil CASCADE;

DROP TABLE IF EXISTS refeicao CASCADE;

DROP TABLE IF EXISTS dia CASCADE;

DROP TABLE IF EXISTS alimento CASCADE;

DROP TABLE IF EXISTS tabela_nutricional CASCADE;

DROP TABLE IF EXISTS codigo_de_barras CASCADE;

DROP TABLE IF EXISTS alimento_favoritado CASCADE;

DROP TABLE IF EXISTS prato CASCADE;

DROP TABLE IF EXISTS alimento_prato CASCADE;

DROP TABLE IF EXISTS alimento_consumido CASCADE;