#!/usr/bin/env node
// Starts NutrIA for local development in one shot, cross-platform (Windows/Mac/Linux):
// installs deps if missing, creates .env files if missing (generating JWT
// secrets), starts local Postgres via Docker, runs migrations + seed, starts
// the backend in the background, then starts Expo in the foreground.
'use strict';

const { spawn, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const BACKEND = path.join(ROOT, 'backend');
const FRONTEND = path.join(ROOT, 'frontend');

function log(msg) {
   console.log(`\n==> ${msg}`);
}

function run(cmd, args, opts = {}) {
   const result = spawnSync(cmd, args, { stdio: 'inherit', shell: true, ...opts });
   if (result.status !== 0) {
      process.exit(result.status ?? 1);
   }
}

function sleep(ms) {
   return new Promise((resolve) => setTimeout(resolve, ms));
}

function generateSecret() {
   return crypto.randomBytes(64).toString('base64');
}

async function main() {
   log('Checking dependencies');
   if (!fs.existsSync(path.join(BACKEND, 'node_modules'))) {
      console.log('Installing backend dependencies...');
      run('npm', ['install'], { cwd: BACKEND });
   }
   if (!fs.existsSync(path.join(FRONTEND, 'node_modules'))) {
      console.log('Installing frontend dependencies...');
      run('npm', ['install'], { cwd: FRONTEND });
   }

   log('Checking env files');
   const backendEnvPath = path.join(BACKEND, '.env');
   if (!fs.existsSync(backendEnvPath)) {
      console.log('Creating backend/.env with freshly generated JWT secrets...');
      const example = fs.readFileSync(path.join(BACKEND, '.env.example'), 'utf8');
      const extra = [
         '',
         '# Auto-generated by scripts/dev.js',
         `BACKEND_JWT_SECRET=${generateSecret()}`,
         `BACKEND_REFRESH_SECRET=${generateSecret()}`,
         '',
      ].join('\n');
      fs.writeFileSync(backendEnvPath, example + extra);
      console.log('    (add BACKEND_OPEN_AI_API_KEY to backend/.env later if you want the chatbot to work)');
   }
   const frontendEnvPath = path.join(FRONTEND, '.env');
   if (!fs.existsSync(frontendEnvPath)) {
      console.log('Creating frontend/.env from example...');
      fs.copyFileSync(path.join(FRONTEND, '.env.example'), frontendEnvPath);
   }

   const backendEnvContent = fs.readFileSync(backendEnvPath, 'utf8');
   const usingRemoteDb = /^BACKEND_DATABASE_URL=.+$/m.test(backendEnvContent);

   if (!usingRemoteDb) {
      log('Starting local Postgres (Docker)');
      run('docker', ['compose', 'up', '-d'], { cwd: BACKEND });

      log('Waiting for Postgres to accept connections');
      for (;;) {
         const check = spawnSync('docker', ['compose', 'exec', '-T', 'db', 'pg_isready', '-U', 'nutria'], {
            cwd: BACKEND,
            shell: true,
            stdio: 'ignore',
         });
         if (check.status === 0) break;
         await sleep(1000);
      }
   } else {
      log('BACKEND_DATABASE_URL set in backend/.env — skipping local Docker Postgres');
   }

   log('Running migrations');
   run('npm', ['run', 'db:migrate'], { cwd: BACKEND });

   log('Seeding verified foods');
   run('npm', ['run', 'db:seed'], { cwd: BACKEND });

   log('Starting backend (background, http://localhost:5001)');
   // detached so the backend gets its own process group on POSIX — needed
   // below to kill the whole npm -> tsx -> node tree, not just the immediate
   // shell (shell:true wraps the command in /bin/sh, and TERM-ing that alone
   // leaves the real node process running behind).
   const backend = spawn('npm', ['run', 'dev'], { cwd: BACKEND, stdio: 'inherit', shell: true, detached: process.platform !== 'win32' });

   let shuttingDown = false;
   const shutdown = () => {
      if (shuttingDown || backend.exitCode !== null) return;
      shuttingDown = true;
      console.log('\n==> Stopping backend...');
      if (process.platform === 'win32') {
         // shell:true spawns cmd.exe wrapping npm/node; killing just the cmd.exe
         // PID leaves the real process running, so kill the whole tree instead.
         spawnSync('taskkill', ['/pid', String(backend.pid), '/T', '/F']);
      } else {
         try {
            process.kill(-backend.pid, 'SIGTERM');
         } catch {
            backend.kill('SIGTERM');
         }
      }
   };

   process.on('SIGINT', () => { shutdown(); process.exit(0); });
   process.on('SIGTERM', () => { shutdown(); process.exit(0); });

   await sleep(1000);

   log('Starting Expo (frontend) — press Ctrl+C to stop both');
   const frontend = spawn('npm', ['start'], { cwd: FRONTEND, stdio: 'inherit', shell: true });

   frontend.on('exit', (code) => {
      shutdown();
      process.exit(code ?? 0);
   });
}

main().catch((err) => {
   console.error(err);
   process.exit(1);
});
